---
dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    timeout: 1000
    directories:
        - $HOME/miniconda3_$TRAVIS_OS_NAME
        - $TRAVIS_BUILD_DIR/.snakemake/conda    # snakemake envs

before_install: |
    url="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    if [[ -d "$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin ]]; then
        echo "miniconda already installed."
    else
        echo "Installing miniconda."
        mkdir -p "$HOME"/download
        wget \
            --continue \
            --output-document "$HOME"/download/miniconda_"$TRAVIS_OS_NAME".sh \
            $url
        chmod +x "$HOME"/download/miniconda_"$TRAVIS_OS_NAME".sh
        "$HOME"/download/miniconda_"$TRAVIS_OS_NAME".sh \
            -u \
            -b \
            -p "$HOME"/miniconda3_"$TRAVIS_OS_NAME"
        "$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin/conda clean --all --yes
        echo "local_repodata_ttl: 1800" >> ~/.condarc
    fi

install: |
    export PATH="$HOME"/miniconda3_"$TRAVIS_OS_NAME"/bin:"$PATH"
    echo "$PATH"
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda install --quiet --yes --channel bioconda snakemake=5.3.0
    snakemake --use-conda --create-envs-only
    conda clean --all --yes
    pushd src/ || exit
    wget --continue \
    http://downloads.sourceforge.net/project/popoolation/popoolation_1.2.2.zip
    unzip popoolation_1.2.2.zip
    wget --continue \
    http://downloads.sourceforge.net/project/popoolation2/popoolation2_1201.zip
    unzip popoolation2_1201.zip
    popd || exit

script: |
    export PATH="/home/travis/miniconda3/bin:$PATH"
    snakemake --resources memory_gb=3 --use-conda -j

after_failure:
