---

trimmomatic:
    extra: >
        AVGQUAL:3
        MINLEN:31
        LEADING:19
        TRAILING:19
        MINLEN:31
        SLIDINGWINDOW:4:5
        LEADING:5
        TRAILING:5
        MINLEN:25
        TOPHRED33


bwa:
    threads: 40
    extra: ''

bcftools:
